version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 